### PR TITLE
Added AWS EKS to list of Kubernetes clusters

### PR DESCRIPTION
**Pull request by craiglpeters**

### CODE REVIEW

**Review by jainishshah17 — APPROVED** [review]

**Comment by Abu436** [comment]
Abubakar Sani from Nigeria. Really love this software but need some mentor shi

**Comment by ThomasRichard127** [comment]
How did you create this

**Comment by alzbeta1** [comment]
T

**Comment by Martins23568865** [comment]
How do you create this

**Comment by Kokonaing677** [comment]
good

**Comment by Kokonaing677** [comment]
free

**Pull request merged**
